### ISSUE TITLE
Localized description

### ISSUE THREAD

**Issue by talisk** [NSHipster/PasswordRules#1]
In my opinion, the function `PasswordRule.descriptor(for: rules)` will return a string for users. So how do I get a localized description about rules.

**Comment by mattt** [comment]
Hi @talisk. `PasswordRule.descriptor(for: rules)` returns a string suitable for passing to the `UITextInputPasswordRules` initializer or as a `passwordrules` attribute in HTML. You can find the proposed specification of this string [here](https://github.com/whatwg/html/issues/3518). This string isn't intended for display to end users, and can't be localized.
